// Package goproxy implements the Go module proxy protocol on top of
// pika's raw filesystem layer. Three Registry kinds are supported:
//
//   - Local — manual upload only, files served directly from
//     the raw mount with no upstream interaction.
//   - Remote — pull-through cache of an upstream module proxy
//     (proxy.golang.org by default). Cache misses are fetched,
//     written to the raw mount, then served. Mutable endpoints
//     (@v/list, @latest) honour the per-repo MutableTTL.
//   - Virtual — ordered aggregation of sibling local + remote repos
//     in the same namespace. First member with the artifact wins.
//
// Protocol: https://go.dev/ref/mod#goproxy-protocol
//
// Storage layout (under the configured BasePath inside the raw mount):
//
//	{base}/modules/{encoded-module}/
//	├── @v/
//	│   ├── list                         line-delimited versions (cached, derived)
//	│   ├── {version}.info               JSON {Version, Time}
//	│   ├── {version}.mod                go.mod file
//	│   └── {version}.zip                module zip
//	└── @latest                          JSON {Version, Time} (cached, derived)
//
// "Cached, derived" entries are lazily regenerated by the Local
// implementation when missing. The Remote implementation persists
// the upstream's response verbatim so the on-wire bytes survive a
// cache round-trip unchanged.
package goproxy

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"path"
	"sort"
	"strings"
	"time"

	"github.com/rakunlabs/pika/internal/rawfs"
	"github.com/rakunlabs/pika/internal/registry/common"
)

// Common errors. Wrapped with the service-layer sentinels by callers
// so the HTTP layer maps them to status codes automatically.
var (
	ErrNotFound  = errors.New("goproxy: not found")
	ErrConflict  = errors.New("goproxy: already exists")
	ErrBadModule = errors.New("goproxy: invalid module")
)

// VersionInfo is the JSON shape served from @v/{version}.info and
// @latest. The fields are exactly what the spec defines; Origin and
// other optional fields are left out — pika doesn't surface them.
type VersionInfo struct {
	Version string    `json:"Version"`
	Time    time.Time `json:"Time"`
}

// Store is the path-keyed storage layer for one Go registry repo.
// It wraps a rawfs.RawFS scoped to a single mount + base path and
// exposes the verbs every Registry impl needs.
//
// Concurrency: every method is safe for concurrent use. The
// underlying rawfs handles parallel reads; writes coordinate
// through whatever atomicity guarantees the backend provides
// (atomic rename on local/SFTP, last-writer-wins on S3 with
// content-addressable semantics for the @v/{ver}.{ext} files
// because the version is the key).
type Store struct {
	fs       rawfs.RawFS
	basePath string
}

// NewStore wraps the given rawfs in a goproxy Store. basePath is
// the prefix inside the rawfs where modules/ lives; passing "" means
// "use the rawfs root".
func NewStore(fs rawfs.RawFS, basePath string) *Store {
	return &Store{
		fs:       fs,
		basePath: strings.Trim(basePath, "/"),
	}
}

// RawFS exposes the underlying rawfs handle for callers (typically
// upload / pull-through code) that need to write through paths the
// Store doesn't expose directly. Must not be used to bypass the
// store's path conventions.
func (s *Store) RawFS() rawfs.RawFS { return s.fs }

// join joins path segments with the configured base path.
func (s *Store) join(parts ...string) string {
	if s.basePath != "" {
		parts = append([]string{s.basePath}, parts...)
	}
	return path.Join(parts...)
}

// moduleDir returns the rawfs path for a module's directory.
// Module path is encoded via EncodeModulePath; callers pass the
// decoded (canonical) form.
func (s *Store) moduleDir(modulePath string) string {
	return s.join("modules", EncodeModulePath(modulePath))
}

// versionPath returns the rawfs path for a specific {module, version,
// extension} tuple. Extensions: "info", "mod", "zip". Other values
// are accepted verbatim — callers gate the values that reach here.
func (s *Store) versionPath(modulePath, version, ext string) string {
	return path.Join(s.moduleDir(modulePath), "@v", version+"."+ext)
}

// listPath returns the rawfs path for the cached @v/list file.
func (s *Store) listPath(modulePath string) string {
	return path.Join(s.moduleDir(modulePath), "@v", "list")
}

// latestPath returns the rawfs path for the cached @latest file.
func (s *Store) latestPath(modulePath string) string {
	return path.Join(s.moduleDir(modulePath), "@latest")
}

// OpenVersionFile streams a {module, version, ext} file. Returns
// (nil, ErrNotFound) when the file is missing.
func (s *Store) OpenVersionFile(modulePath, version, ext string) (rawfs.ReadSeekCloser, *rawfs.FileInfo, error) {
	key := s.versionPath(modulePath, version, ext)
	rc, fi, err := s.fs.Open(key)
	if err != nil {
		return nil, nil, mapNotFound(err)
	}
	return rc, fi, nil
}

// StatVersionFile probes for existence without opening the file.
func (s *Store) StatVersionFile(modulePath, version, ext string) (*rawfs.FileInfo, error) {
	fi, err := s.fs.Stat(s.versionPath(modulePath, version, ext))
	if err != nil {
		return nil, mapNotFound(err)
	}
	return fi, nil
}

// WriteVersionFile creates or overwrites a {module, version, ext}
// file. Used by Local upload and Remote cache writes. Requires the
// backing rawfs to be writable.
func (s *Store) WriteVersionFile(modulePath, version, ext string, r io.Reader, size int64) error {
	wfs, ok := s.fs.(rawfs.WritableRawFS)
	if !ok {
		return fmt.Errorf("goproxy: backend is read-only")
	}
	key := s.versionPath(modulePath, version, ext)
	if err := wfs.Write(key, r, size); err != nil {
		return fmt.Errorf("goproxy: write %s: %w", key, err)
	}
	// Best-effort invalidate the cached list so the next /@v/list
	// regenerates with this new entry. Failures here are non-fatal
	// — the list cache is just an optimisation.
	_ = wfs.Delete(s.listPath(modulePath))
	_ = wfs.Delete(s.latestPath(modulePath))
	return nil
}

// DeleteVersion removes the .info, .mod, .zip for one version. The
// cached list and latest entries are also invalidated.
func (s *Store) DeleteVersion(modulePath, version string) error {
	wfs, ok := s.fs.(rawfs.WritableRawFS)
	if !ok {
		return fmt.Errorf("goproxy: backend is read-only")
	}
	var firstErr error
	for _, ext := range []string{"info", "mod", "zip"} {
		key := s.versionPath(modulePath, version, ext)
		if err := wfs.Delete(key); err != nil && !isNotFound(err) {
			if firstErr == nil {
				firstErr = err
			}
		}
	}
	_ = wfs.Delete(s.listPath(modulePath))
	_ = wfs.Delete(s.latestPath(modulePath))
	return firstErr
}

// ListVersions enumerates every version present under @v/. The list
// is computed by listing the @v/ directory and gathering filenames
// of the form "{version}.info" (info is the canonical marker — a
// version without .info is considered incomplete and skipped).
//
// Returns versions sorted ascending using semver-ish lexicographic
// order. Real semver sorting (handling pre-release, build metadata)
// is the go client's job once it has the list; here we just need a
// stable order for ETag / list serialisation.
func (s *Store) ListVersions(modulePath string) ([]string, error) {
	dir := path.Join(s.moduleDir(modulePath), "@v")
	entries, err := s.fs.ReadDir(dir)
	if err != nil {
		if isNotFound(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("goproxy: list versions: %w", err)
	}
	var versions []string
	for _, e := range entries {
		if e.IsDir {
			continue
		}
		if !strings.HasSuffix(e.Name, ".info") {
			continue
		}
		v := strings.TrimSuffix(e.Name, ".info")
		if v == "" {
			continue
		}
		versions = append(versions, v)
	}
	sort.Strings(versions)
	return versions, nil
}

// CachedList returns the lazily-derived @v/list content. If a cached
// copy exists and is recent (per ttl, when > 0), it is returned
// verbatim. Otherwise the list is rebuilt from ListVersions and
// written back through the cache.
//
// ttl=0 disables the cache check — the list is rebuilt every call
// (used by Local registries where the cost is negligible).
func (s *Store) CachedList(modulePath string, ttl time.Duration) ([]byte, error) {
	key := s.listPath(modulePath)
	if ttl > 0 {
		if rc, fi, err := s.fs.Open(key); err == nil {
			defer rc.Close()
			if time.Since(fi.ModTime) < ttl {
				return io.ReadAll(rc)
			}
		}
	}
	versions, err := s.ListVersions(modulePath)
	if err != nil {
		return nil, err
	}
	body := []byte(strings.Join(versions, "\n"))
	if len(versions) > 0 {
		body = append(body, '\n')
	}
	// Write-back is best-effort; failure just means we'll rebuild
	// again next time. Skip on read-only backends silently.
	if wfs, ok := s.fs.(rawfs.WritableRawFS); ok {
		_ = wfs.Write(key, strings.NewReader(string(body)), int64(len(body)))
	}
	return body, nil
}

// CachedLatest returns the lazily-derived @latest content (a JSON
// blob carrying the most recent version). If no cached copy is
// fresh, the file is rebuilt by reading the highest version's
// .info. Returns ErrNotFound when the module has no versions yet.
func (s *Store) CachedLatest(modulePath string, ttl time.Duration) ([]byte, error) {
	key := s.latestPath(modulePath)
	if ttl > 0 {
		if rc, fi, err := s.fs.Open(key); err == nil {
			defer rc.Close()
			if time.Since(fi.ModTime) < ttl {
				return io.ReadAll(rc)
			}
		}
	}
	versions, err := s.ListVersions(modulePath)
	if err != nil {
		return nil, err
	}
	if len(versions) == 0 {
		return nil, ErrNotFound
	}
	// Sort is lexicographic; for proper semver "latest" we'd want
	// golang.org/x/mod/semver.Sort. For MVP, take the last entry —
	// most published modules follow vX.Y.Z and lexicographic order
	// matches semver order for two-digit components. Real-world
	// sorting can be added when the first user reports drift.
	latestVer := versions[len(versions)-1]
	rc, _, err := s.OpenVersionFile(modulePath, latestVer, "info")
	if err != nil {
		return nil, fmt.Errorf("goproxy: read latest info: %w", err)
	}
	defer rc.Close()
	body, err := io.ReadAll(rc)
	if err != nil {
		return nil, err
	}
	if wfs, ok := s.fs.(rawfs.WritableRawFS); ok {
		_ = wfs.Write(key, strings.NewReader(string(body)), int64(len(body)))
	}
	return body, nil
}

// ListModules walks the modules/ tree and returns every module
// (decoded form) that has at least one version on disk. Used by the
// admin UI for the per-repo module browser.
func (s *Store) ListModules() ([]string, error) {
	root := s.join("modules")
	out, err := walkModules(s.fs, root, "")
	if err != nil {
		if isNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	sort.Strings(out)
	return out, nil
}

// walkModules recursively traverses the module directory tree. A
// directory is treated as a "module leaf" when it contains an
// @v subdirectory. The walk is depth-first because module paths
// have variable depth ("k8s.io/api" vs "github.com/foo/bar/v2").
func walkModules(fs rawfs.RawFS, dir, prefix string) ([]string, error) {
	entries, err := fs.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir {
			continue
		}
		// Detect a module leaf: this dir contains "@v".
		atV := path.Join(dir, e.Name, "@v")
		if _, err := fs.Stat(atV); err == nil {
			mod := prefix
			if mod != "" {
				mod += "/"
			}
			mod += e.Name
			decoded, err := DecodeModulePath(mod)
			if err != nil {
				continue
			}
			out = append(out, decoded)
			continue
		}
		// Otherwise descend.
		sub, err := walkModules(fs, path.Join(dir, e.Name), joinPrefix(prefix, e.Name))
		if err != nil {
			// Non-fatal — surface the modules we did find.
			continue
		}
		out = append(out, sub...)
	}
	return out, nil
}

func joinPrefix(prefix, seg string) string {
	if prefix == "" {
		return seg
	}
	return prefix + "/" + seg
}

// WriteInfo serialises a VersionInfo as the .info file body and
// writes it. Convenience over WriteVersionFile + manual JSON
// marshalling.
func (s *Store) WriteInfo(modulePath, version string, info VersionInfo) error {
	body, err := json.Marshal(info)
	if err != nil {
		return fmt.Errorf("goproxy: marshal info: %w", err)
	}
	return s.WriteVersionFile(modulePath, version, "info", strings.NewReader(string(body)), int64(len(body)))
}

// EtagForList computes a cache validator for an @v/list payload.
// The same versions in the same order produce the same etag.
func EtagForList(body []byte) string {
	return common.EtagFor(string(body))
}

// mapNotFound translates a rawfs "not found" error into the package
// sentinel so callers can errors.Is on ErrNotFound uniformly.
func mapNotFound(err error) error {
	if err == nil {
		return nil
	}
	if isNotFound(err) {
		return ErrNotFound
	}
	return err
}

func isNotFound(err error) bool {
	if err == nil {
		return false
	}
	low := strings.ToLower(err.Error())
	return strings.Contains(low, "not found") ||
		strings.Contains(low, "no such file") ||
		strings.Contains(low, "does not exist")
}
