// Package goproxy implements the Go module proxy protocol on top of
// pika's raw filesystem layer. Three Registry kinds are supported:
//
//   - Local — manual upload only, files served directly from
//     the raw mount with no upstream interaction.
//   - Remote — pull-through cache of an upstream module proxy
//     (proxy.golang.org by default). Cache misses are fetched,
//     written to the raw mount, then served. Mutable endpoints
//     (@v/list, @latest) honour the per-repo MutableTTL.
//   - Virtual — ordered aggregation of sibling local + remote repos
//     in the same namespace. First member with the artifact wins.
//
// Protocol: https://go.dev/ref/mod#goproxy-protocol
//
// Storage layout (under the configured BasePath inside the raw mount):
//
//	{base}/modules/{encoded-module}/
//	├── @v/
//	│   ├── list                         line-delimited versions (cached, derived)
//	│   ├── {version}.info               JSON {Version, Time}
//	│   ├── {version}.mod                go.mod file
//	│   └── {version}.zip                module zip
//	└── @latest                          JSON {Version, Time} (cached, derived)
//
// "Cached, derived" entries are lazily regenerated by the Local
// implementation when missing. The Remote implementation persists
// the upstream's response verbatim so the on-wire bytes survive a
// cache round-trip unchanged.
package goproxy

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"path"
	"sort"
	"strings"
	"time"

	"github.com/rakunlabs/pika/internal/rawfs"
	"github.com/rakunlabs/pika/internal/registry/common"
)

// Common errors. Wrapped with the service-layer sentinels by callers
// so the HTTP layer maps them to status codes automatically.
var (
	ErrNotFound  = errors.New("goproxy: not found")
	ErrConflict  = errors.New("goproxy: already exists")
	ErrBadModule = errors.New("goproxy: invalid module")
)

// VersionInfo is the JSON shape served from @v/{version}.info and
// @latest. The fields are exactly what the spec defines; Origin and
// other optional fields are left out — pika doesn't surface them.
type VersionInfo struct {
	Version string    `json:"Version"`
	Time    time.Time `json:"Time"`
}

// Store is the path-keyed storage layer for one Go registry repo.
// It wraps a rawfs.RawFS scoped to a single mount + base path and
// exposes the verbs every Registry impl needs.
//
// Concurrency: every method is safe for concurrent use. The
// underlying rawfs handles parallel reads; writes coordinate
// through whatever atomicity guarantees the backend provides
// (atomic rename on local/SFTP, last-writer-wins on S3 with
// content-addressable semantics for the @v/{ver}.{ext} files
// because the version is the key).
type Store struct {
	fs       rawfs.RawFS
	basePath string
}

// NewStore wraps the given rawfs in a goproxy Store. basePath is
// the prefix inside the rawfs where modules/ lives; passing "" means
// "use the rawfs root".
func NewStore(fs rawfs.RawFS, basePath string) *Store {
	return &Store{
		fs:       fs,
		basePath: strings.Trim(basePath, "/"),
	}
}

// RawFS exposes the underlying rawfs handle for callers (typically
// upload / pull-through code) that need to write through paths the
// Store doesn't expose directly. Must not be used to bypass the
// store's path conventions.
func (s *Store) RawFS() rawfs.RawFS { return s.fs }

// join joins path segments with the configured base path.
func (s *Store) join(parts ...string) string {
	if s.basePath != "" {
		parts = append([]string{s.basePath}, parts...)
	}
	return path.Join(parts...)
}

// moduleDir returns the rawfs path for a module's directory.
// Module path is encoded via EncodeModulePath; callers pass the
// decoded (canonical) form.
func (s *Store) moduleDir(modulePath string) string {
	return s.join("modules", EncodeModulePath(modulePath))
}

// versionPath returns the rawfs path for a specific {module, version,
// extension} tuple. Extensions: "info", "mod", "zip". Other values
// are accepted verbatim — callers gate the values that reach here.
func (s *Store) versionPath(modulePath, version, ext string) string {
	return path.Join(s.moduleDir(modulePath), "@v", version+"."+ext)
}

// listPath returns the rawfs path for the cached @v/list file.
func (s *Store) listPath(modulePath string) string {
	return path.Join(s.moduleDir(modulePath), "@v", "list")
}

// latestPath returns the rawfs path for the cached @latest file.
func (s *Store) latestPath(modulePath string) string {
	return path.Join(s.moduleDir(modulePath), "@latest")
}

// OpenVersionFile streams a {module, version, ext} file. Returns
// (nil, ErrNotFound) when the file is missing.
func (s *Store) OpenVersionFile(modulePath, version, ext string) (rawfs.ReadSeekCloser, *rawfs.FileInfo, error) {
	key := s.versionPath(modulePath, version, ext)
	rc, fi, err := s.fs.Open(key)
	if err != nil {
		return nil, nil, mapNotFound(err)
	}
	return rc, fi, nil
}

// StatVersionFile probes for existence without opening the file.
func (s *Store) StatVersionFile(modulePath, version, ext string) (*rawfs.FileInfo, error) {
	fi, err := s.fs.Stat(s.versionPath(modulePath, version, ext))
	if err != nil {
		return nil, mapNotFound(err)
	}
	return fi, nil
}

// WriteVersionFile creates or overwrites a {module, version, ext}
// file. Used by Local upload and Remote cache writes. Requires the
// backing rawfs to be writable.
func (s *Store) WriteVersionFile(modulePath, version, ext string, r io.Reader, size int64) error {
	wfs, ok := s.fs.(rawfs.WritableRawFS)
	if !ok {
		return fmt.Errorf("goproxy: backend is read-only")
	}
	key := s.versionPath(modulePath, version, ext)
	if err := wfs.Write(key, r, size); err != nil {
		return fmt.Errorf("goproxy: write %s: %w", key, err)
	}
	// Best-effort invalidate the cached list so the next /@v/list
	// regenerates with this new entry. Failures here are non-fatal
	// — the list cache is just an optimisation.
	_ = wfs.Delete(s.listPath(modulePath))
	_ = wfs.Delete(s.latestPath(modulePath))
	return nil
}

// DeleteVersion removes the .info, .mod, .zip for one version. The
// cached list and latest entries are also invalidated.
func (s *Store) DeleteVersion(modulePath, version string) error {
	wfs, ok := s.fs.(rawfs.WritableRawFS)
	if !ok {
		return fmt.Errorf("goproxy: backend is read-only")
	}
	var firstErr error
	for _, ext := range []string{"info", "mod", "zip"} {
		key := s.versionPath(modulePath, version, ext)
		if err := wfs.Delete(key); err != nil && !isNotFound(err) {
			if firstErr == nil {
				firstErr = err
			}
		}
	}
	_ = wfs.Delete(s.listPath(modulePath))
	_ = wfs.Delete(s.latestPath(modulePath))
	return firstErr
}

// ListVersions enumerates every version present under @v/. Local
// repos use .info as the canonical marker; Remote caches may only
// have upstream @v/list or @latest bodies, so those markers are
// folded in as well for the admin browser.
//
// Returns versions sorted ascending using semver-ish lexicographic
// order. Real semver sorting (handling pre-release, build metadata)
// is the go client's job once it has the list; here we just need a
// stable order for ETag / list serialisation.
func (s *Store) ListVersions(modulePath string) ([]string, error) {
	seen := map[string]struct{}{}
	dir := path.Join(s.moduleDir(modulePath), "@v")
	entries, err := s.fs.ReadDir(dir)
	if err != nil && !isNotFound(err) {
		return nil, fmt.Errorf("goproxy: list versions: %w", err)
	}
	if err == nil {
		for _, e := range entries {
			if e.IsDir {
				continue
			}
			if !strings.HasSuffix(e.Name, ".info") {
				continue
			}
			v := strings.TrimSuffix(e.Name, ".info")
			if v == "" {
				continue
			}
			seen[v] = struct{}{}
		}
	}

	if listVersions, err := s.cachedListVersions(modulePath); err == nil {
		for _, v := range listVersions {
			seen[v] = struct{}{}
		}
	} else if !isNotFound(err) {
		return nil, err
	}
	if latest, err := s.cachedLatestVersion(modulePath); err == nil && latest != "" {
		seen[latest] = struct{}{}
	} else if err != nil && !isNotFound(err) {
		return nil, err
	}

	versions := make([]string, 0, len(seen))
	for v := range seen {
		versions = append(versions, v)
	}
	sort.Strings(versions)
	return versions, nil
}

func (s *Store) cachedListVersions(modulePath string) ([]string, error) {
	rc, _, err := s.fs.Open(s.listPath(modulePath))
	if err != nil {
		if isNotFound(err) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("goproxy: open cached list: %w", err)
	}
	defer rc.Close()
	body, err := io.ReadAll(rc)
	if err != nil {
		return nil, fmt.Errorf("goproxy: read cached list: %w", err)
	}
	var versions []string
	for _, line := range strings.Split(string(body), "\n") {
		v := strings.TrimSpace(line)
		if v == "" {
			continue
		}
		versions = append(versions, v)
	}
	return versions, nil
}

func (s *Store) cachedLatestVersion(modulePath string) (string, error) {
	rc, _, err := s.fs.Open(s.latestPath(modulePath))
	if err != nil {
		if isNotFound(err) {
			return "", ErrNotFound
		}
		return "", fmt.Errorf("goproxy: open cached latest: %w", err)
	}
	defer rc.Close()
	body, err := io.ReadAll(rc)
	if err != nil {
		return "", fmt.Errorf("goproxy: read cached latest: %w", err)
	}
	var info VersionInfo
	if err := json.Unmarshal(body, &info); err != nil {
		return "", nil
	}
	return strings.TrimSpace(info.Version), nil
}

// CachedList returns the lazily-derived @v/list content. If a cached
// copy exists and is recent (per ttl, when > 0), it is returned
// verbatim. Otherwise the list is rebuilt from ListVersions and
// written back through the cache.
//
// ttl=0 disables the cache check — the list is rebuilt every call
// (used by Local registries where the cost is negligible).
func (s *Store) CachedList(modulePath string, ttl time.Duration) ([]byte, error) {
	key := s.listPath(modulePath)
	if ttl > 0 {
		if rc, fi, err := s.fs.Open(key); err == nil {
			defer rc.Close()
			if time.Since(fi.ModTime) < ttl {
				return io.ReadAll(rc)
			}
		}
	}
	versions, err := s.ListVersions(modulePath)
	if err != nil {
		return nil, err
	}
	body := []byte(strings.Join(versions, "\n"))
	if len(versions) > 0 {
		body = append(body, '\n')
	}
	// Write-back is best-effort; failure just means we'll rebuild
	// again next time. Skip on read-only backends silently.
	if wfs, ok := s.fs.(rawfs.WritableRawFS); ok {
		_ = wfs.Write(key, strings.NewReader(string(body)), int64(len(body)))
	}
	return body, nil
}

// CachedLatest returns the lazily-derived @latest content (a JSON
// blob carrying the most recent version). If no cached copy is
// fresh, the file is rebuilt by reading the highest version's
// .info. Returns ErrNotFound when the module has no versions yet.
func (s *Store) CachedLatest(modulePath string, ttl time.Duration) ([]byte, error) {
	key := s.latestPath(modulePath)
	if ttl > 0 {
		if rc, fi, err := s.fs.Open(key); err == nil {
			defer rc.Close()
			if time.Since(fi.ModTime) < ttl {
				return io.ReadAll(rc)
			}
		}
	}
	versions, err := s.ListVersions(modulePath)
	if err != nil {
		return nil, err
	}
	if len(versions) == 0 {
		return nil, ErrNotFound
	}
	// Sort semver-aware so v10.x.y outranks v2.x.y. ListVersions
	// returns lex order; SortVersionsDesc gives us newest-first,
	// from which we pick index 0.
	SortVersionsDesc(versions)
	latestVer := versions[0]
	rc, _, err := s.OpenVersionFile(modulePath, latestVer, "info")
	if err != nil {
		return nil, fmt.Errorf("goproxy: read latest info: %w", err)
	}
	defer rc.Close()
	body, err := io.ReadAll(rc)
	if err != nil {
		return nil, err
	}
	if wfs, ok := s.fs.(rawfs.WritableRawFS); ok {
		_ = wfs.Write(key, strings.NewReader(string(body)), int64(len(body)))
	}
	return body, nil
}

// ListModules walks the modules/ tree and returns every module
// (decoded form) that has at least one version on disk. Used by the
// admin UI for the per-repo module browser.
func (s *Store) ListModules() ([]string, error) {
	root := s.join("modules")
	out, err := walkModules(s.fs, root, "")
	if err != nil {
		if isNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	sort.Strings(out)
	return out, nil
}

// walkModules recursively traverses the module directory tree. A
// directory is treated as a "module leaf" when it contains an
// @v subdirectory. The walk is depth-first because module paths
// have variable depth ("k8s.io/api" vs "github.com/foo/bar/v2").
func walkModules(fs rawfs.RawFS, dir, prefix string) ([]string, error) {
	entries, err := fs.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir {
			continue
		}
		child := path.Join(dir, e.Name)
		// Detect a module leaf: this dir contains cached version
		// markers. Still descend afterwards because Go modules can be
		// nested (e.g. github.com/acme/root and github.com/acme/root/sub).
		if moduleDirHasVersionMarkers(fs, child) {
			mod := prefix
			if mod != "" {
				mod += "/"
			}
			mod += e.Name
			decoded, err := DecodeModulePath(mod)
			if err != nil {
				continue
			}
			out = append(out, decoded)
		}
		// Otherwise descend.
		sub, err := walkModules(fs, child, joinPrefix(prefix, e.Name))
		if err != nil {
			// Non-fatal — surface the modules we did find.
			continue
		}
		out = append(out, sub...)
	}
	return out, nil
}

func moduleDirHasVersionMarkers(fs rawfs.RawFS, dir string) bool {
	atV := path.Join(dir, "@v")
	if entries, err := fs.ReadDir(atV); err == nil {
		for _, e := range entries {
			if e.IsDir {
				continue
			}
			if e.Name == "list" || strings.HasSuffix(e.Name, ".info") {
				return true
			}
		}
	}
	if _, err := fs.Stat(path.Join(dir, "@latest")); err == nil {
		return true
	}
	return false
}

func joinPrefix(prefix, seg string) string {
	if prefix == "" {
		return seg
	}
	return prefix + "/" + seg
}

// WriteInfo serialises a VersionInfo as the .info file body and
// writes it. Convenience over WriteVersionFile + manual JSON
// marshalling.
func (s *Store) WriteInfo(modulePath, version string, info VersionInfo) error {
	body, err := json.Marshal(info)
	if err != nil {
		return fmt.Errorf("goproxy: marshal info: %w", err)
	}
	return s.WriteVersionFile(modulePath, version, "info", strings.NewReader(string(body)), int64(len(body)))
}

// EtagForList computes a cache validator for an @v/list payload.
// The same versions in the same order produce the same etag.
func EtagForList(body []byte) string {
	return common.EtagFor(string(body))
}

// ReadVersionInfo reads and JSON-decodes the @v/{version}.info
// file into a VersionInfo. Returns (zero, ErrNotFound) when the
// file is missing. Used by the package-detail builder to gather
// publish timestamps.
func (s *Store) ReadVersionInfo(modulePath, version string) (VersionInfo, error) {
	rc, _, err := s.OpenVersionFile(modulePath, version, "info")
	if err != nil {
		return VersionInfo{}, err
	}
	defer rc.Close()
	body, err := io.ReadAll(rc)
	if err != nil {
		return VersionInfo{}, err
	}
	var info VersionInfo
	if jerr := json.Unmarshal(body, &info); jerr != nil {
		// .info is supposed to be JSON {Version,Time}; treat a
		// parse failure as a soft miss so the caller can still
		// render the version row with whatever it has.
		return VersionInfo{Version: version}, nil
	}
	return info, nil
}

// ReadGoMod returns the raw bytes of the @v/{version}.mod file.
// Used by the detail UI's go.mod viewer.
func (s *Store) ReadGoMod(modulePath, version string) ([]byte, error) {
	rc, _, err := s.OpenVersionFile(modulePath, version, "mod")
	if err != nil {
		return nil, err
	}
	defer rc.Close()
	return io.ReadAll(rc)
}

// VersionSize returns the size in bytes of the .{ext} file for the
// given version, or 0 (no error) when the file does not exist.
// Used by the detail UI to surface per-version artifact sizes
// without forcing the caller to open the file.
func (s *Store) VersionSize(modulePath, version, ext string) int64 {
	fi, err := s.fs.Stat(s.versionPath(modulePath, version, ext))
	if err != nil {
		return 0
	}
	return fi.Size
}

// LatestVersionSemver picks the semver-highest version present in
// @v/. Returns "" when the module has no versions. Mirrors the
// CachedLatest logic but without the JSON wrapping — the caller
// (e.g. detail builder) wants just the version string.
func (s *Store) LatestVersionSemver(modulePath string) string {
	versions, _ := s.ListVersions(modulePath)
	if len(versions) == 0 {
		return ""
	}
	SortVersionsDesc(versions)
	return versions[0]
}

// CountModulesVersionsBytes walks the modules tree once and returns
// (#modules, #versions across all modules, total bytes of every
// .info/.mod/.zip plus the cached list/latest files). Used by the
// stats endpoint; intentionally a single function so both Local
// and Remote share the implementation.
//
// Errors during traversal are non-fatal: the walk continues so the
// caller sees a best-effort accounting rather than a zero.
func (s *Store) CountModulesVersionsBytes() (modules int, versions int, bytes int64) {
	mods, _ := s.ListModules()
	modules = len(mods)
	for _, mod := range mods {
		atV := path.Join(s.moduleDir(mod), "@v")
		entries, err := s.fs.ReadDir(atV)
		if err != nil {
			continue
		}
		for _, e := range entries {
			if e.IsDir {
				continue
			}
			// .info files are the canonical "this version exists"
			// marker. Counting them matches the spec ("list" is
			// derived from .info presence) so a partial upload
			// without .info doesn't inflate the count.
			if strings.HasSuffix(e.Name, ".info") {
				versions++
			}
			if fi, err := s.fs.Stat(path.Join(atV, e.Name)); err == nil {
				bytes += fi.Size
			}
		}
		// Also account the latestPath if present.
		if fi, err := s.fs.Stat(s.latestPath(mod)); err == nil {
			bytes += fi.Size
		}
	}
	return
}

// PurgeMutable removes every cached "mutable" pointer (the
// per-module @v/list and @latest files) so the next request for
// either re-resolves through upstream. Immutable .info / .mod /
// .zip files are intentionally preserved — they're content-tagged
// by version and never change upstream-side.
//
// Returns (count, bytes) of files actually deleted. The walk is
// best-effort: a Delete failure on one file is recorded in the
// returned error slice but does not stop the rest of the purge.
func (s *Store) PurgeMutable() (int, int64, []error) {
	wfs, ok := s.fs.(rawfs.WritableRawFS)
	if !ok {
		return 0, 0, []error{fmt.Errorf("goproxy: backend is read-only")}
	}
	modules, _ := s.ListModules()
	var (
		count int
		bytes int64
		errs  []error
	)
	for _, mod := range modules {
		for _, p := range []string{s.listPath(mod), s.latestPath(mod)} {
			if fi, err := s.fs.Stat(p); err == nil {
				if delErr := wfs.Delete(p); delErr == nil {
					count++
					bytes += fi.Size
				} else if !isNotFound(delErr) {
					errs = append(errs, fmt.Errorf("delete %s: %w", p, delErr))
				}
			}
		}
	}
	return count, bytes, errs
}

// PurgeAll wipes the entire module cache: every @v/list, @latest,
// .info, .mod and .zip under {base}/modules/. Used by Remote
// repositories to force a complete re-download on the next pull.
// Local repositories should NOT call this — it would discard
// operator-uploaded artifacts.
//
// Returns (count, bytes) of files actually deleted, plus any
// per-file errors (walk continues on error).
func (s *Store) PurgeAll() (int, int64, []error) {
	wfs, ok := s.fs.(rawfs.WritableRawFS)
	if !ok {
		return 0, 0, []error{fmt.Errorf("goproxy: backend is read-only")}
	}
	modules, _ := s.ListModules()
	var (
		count int
		bytes int64
		errs  []error
	)
	for _, mod := range modules {
		// Mutable pointers first.
		for _, p := range []string{s.listPath(mod), s.latestPath(mod)} {
			if fi, err := s.fs.Stat(p); err == nil {
				if delErr := wfs.Delete(p); delErr == nil {
					count++
					bytes += fi.Size
				}
			}
		}
		// Then every .info / .mod / .zip under @v.
		atV := path.Join(s.moduleDir(mod), "@v")
		entries, err := s.fs.ReadDir(atV)
		if err != nil {
			continue
		}
		for _, e := range entries {
			if e.IsDir {
				continue
			}
			p := path.Join(atV, e.Name)
			fi, statErr := s.fs.Stat(p)
			if statErr != nil {
				continue
			}
			if delErr := wfs.Delete(p); delErr == nil {
				count++
				bytes += fi.Size
			} else if !isNotFound(delErr) {
				errs = append(errs, fmt.Errorf("delete %s: %w", p, delErr))
			}
		}
	}
	return count, bytes, errs
}

// mapNotFound translates a rawfs "not found" error into the package
// sentinel so callers can errors.Is on ErrNotFound uniformly.
func mapNotFound(err error) error {
	if err == nil {
		return nil
	}
	if isNotFound(err) {
		return ErrNotFound
	}
	return err
}

func isNotFound(err error) bool {
	if err == nil {
		return false
	}
	low := strings.ToLower(err.Error())
	return strings.Contains(low, "not found") ||
		strings.Contains(low, "no such file") ||
		strings.Contains(low, "does not exist")
}
