apiVersion: v1
kind: ConfigMap
metadata:
  name: pika
data:
  config.yaml: |
    log_level: info
    server:
      port: "8080"
      public_port: "9090"
      auth:
        session_ttl: 24h
        cookie:
          secure: true
          same_site: lax
    storage:
      path: /data/pika.db
