apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pika

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml

images:
  - name: ghcr.io/rakunlabs/pika
    newTag: latest
