package service

import (
	"errors"
	"fmt"
	"net"
	"regexp"
	"strconv"
	"strings"
	"text/template"
	"time"
)

// PublicEndpoint is one operator-defined public HTTP endpoint that
// returns pika configuration data directly, through a compatibility
// shim (e.g. Consul KV), directly from an External resource, or
// through a custom Go template modifier.
//
// Each endpoint owns its own TCP listener (Host:Port) and base path.
// The runtime side lives in internal/server/publicendpoint; the
// service layer just persists the configuration.
//
// Endpoints are stored inline on Settings (like Hooks) — they are
// few, edited together, and reload as a single batch on every save.
type PublicEndpoint struct {
	// ID is a stable opaque identifier. Generated by the server when
	// the operator creates a new endpoint; clients must not invent
	// their own IDs. Used by the manager to diff old vs new state.
	ID string `json:"id"`
	// Name is an operator-facing label. No uniqueness constraint.
	Name string `json:"name"`
	// Enabled gates the listener. Disabled endpoints stay in
	// settings but bind no port — useful for keeping configuration
	// around while temporarily turning a shim off.
	Enabled bool `json:"enabled"`
	// ListenHost is the bind address. Empty defaults to "0.0.0.0".
	// Use "127.0.0.1" to expose only on loopback.
	ListenHost string `json:"listen_host"`
	// ListenPort is the TCP port. Required, 1..65535. Must not
	// collide with the main pika server port or another endpoint.
	ListenPort int `json:"listen_port"`
	// BasePath is the URL prefix the mode mounts under. Must start
	// with "/" and have no trailing slash. Default "/".
	BasePath string `json:"base_path"`
	// Mode picks the response shape.
	//
	//   "static" — plain config response. The path tail maps onto a
	//              pika config key and the resolved bytes are returned
	//              directly, same as /data/{key}. No templates.
	//   "consul" — read-only Consul KV compatibility shim. Mounts
	//              {BasePath}/v1/kv/{*key} returning Consul-shaped
	//              JSON or raw bytes with ?raw.
	//   "external" — direct read from one configured External resource.
	//                The path tail maps to provider-specific path.
	//   "custom" — user-authored Go template. The {*key} path tail
	//              maps onto a pika config key; the template renders
	//              the response body and Content-Type.
	Mode string `json:"mode"`
	// Static holds static-response configuration. Required when
	// Mode=="static"; ignored otherwise.
	Static *StaticCompat `json:"static,omitempty"`
	// Consul holds Consul-shim configuration. Required when
	// Mode=="consul"; ignored otherwise.
	Consul *ConsulCompat `json:"consul,omitempty"`
	// External holds direct external-resource configuration. Required
	// when Mode=="external"; ignored otherwise.
	External *ExternalCompat `json:"external,omitempty"`
	// Custom holds custom-template configuration. Required when
	// Mode=="custom"; ignored otherwise.
	Custom *CustomCompat `json:"custom,omitempty"`
	// Auth controls how the endpoint authenticates incoming
	// requests. Default Mode="none" (no auth — operator's choice).
	Auth EndpointAuth `json:"auth"`
	// TLS controls whether this endpoint listener accepts HTTPS. When
	// enabled, it uses the server-managed certificate from the main
	// Pika certificate manager. Existing endpoints with a missing block
	// remain HTTP-only.
	TLS EndpointTLS `json:"tls,omitempty"`
	// RequestCheck is an optional declarative rule stage that runs
	// AFTER auth and BEFORE the mode-specific shim. Rules can allow,
	// block, or modify the request before it reaches the shim.
	// When nil, the stage is a no-op pass-through.
	RequestCheck *RequestCheck `json:"request_check,omitempty"`
	// CreatedAt / UpdatedAt are server-managed timestamps surfaced
	// to the UI. The bw row mirrors them but they're carried here
	// as plain time values so the SPA never has to parse two shapes.
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// RequestCheck is the per-endpoint request inspector / modifier
// stage. It runs as middleware between auth and the shim and is
// expressed as an ordered list of operator-defined rules — no
// templates, no JSON to author by hand.
//
// Each rule is evaluated in order. A rule matches when every entry
// in its When block matches the current request (AND semantics).
// On match the rule's Then action runs:
//
//   - "allow"       — short-circuits to the shim. Subsequent rules
//     do not run.
//   - "block"       — short-circuits with the configured status +
//     body. Subsequent rules do not run.
//   - "set_header"  — sets a request header on the way to the shim,
//     then evaluation continues with the next rule.
//   - "del_header"  — removes a request header, then continues.
//   - "set_query"   — sets a query parameter, then continues.
//   - "del_query"   — removes a query parameter, then continues.
//   - "set_path"    — replaces the full URL path literally, then continues.
//   - "replace_path" — regex-replaces the URL path, then continues.
//
// Newer rules may carry Actions instead of Then. Actions are run
// in order; allow/block are terminal and skip any later actions.
// Then is kept for old single-action settings.
//
// If no rule short-circuits with allow/block, the request falls
// through to the shim (default-allow). This is the behaviour
// operators expect from gateway rule lists like Traefik or NGINX:
// modify-stack first, terminal decision last.
type RequestCheck struct {
	// Rules is evaluated top-to-bottom on every request. An empty
	// list disables the stage entirely (parent field can also be
	// left nil — both forms behave the same).
	Rules []RequestRule `json:"rules,omitempty"`
}

// RequestRule is one row in the operator's rule list.
type RequestRule struct {
	// Name is an optional operator-facing label. Surfaced in
	// status logs / future per-rule metrics. Does not affect
	// evaluation.
	Name string `json:"name,omitempty"`
	// Enabled gates evaluation. Disabled rules are kept in the
	// list so an operator can flip them on/off without losing
	// the configuration.
	Enabled bool `json:"enabled"`
	// When holds the matcher predicates. All non-empty fields
	// must match for the rule to fire (AND semantics). An empty
	// When block matches every request.
	When RequestMatch `json:"when"`
	// Then is the action to take on match.
	Then RequestAction `json:"then"`
	// Actions is the ordered multi-action form. When non-empty it takes
	// precedence over Then. Kept separate so persisted single-action
	// rules continue to unmarshal and run unchanged.
	Actions []RequestAction `json:"actions,omitempty"`
}

// RequestMatch is the AND-combined set of predicates a rule
// evaluates against the current request. Empty / unset fields are
// no-ops (i.e. they match anything), so a rule with an empty
// When matches every request.
type RequestMatch struct {
	// Method, when set, must equal the request method (case
	// insensitive). e.g. "GET".
	Method string `json:"method,omitempty"`
	// PathEquals matches the full request URL path verbatim.
	PathEquals string `json:"path_equals,omitempty"`
	// PathPrefix matches a leading substring of the URL path.
	PathPrefix string `json:"path_prefix,omitempty"`
	// HeaderEquals fires when the named header's first value is
	// exactly the given string (case-sensitive value, case-
	// insensitive name via http.CanonicalHeaderKey).
	HeaderEquals *HeaderMatch `json:"header_equals,omitempty"`
	// HeaderPresent fires when the named header has at least one
	// non-empty value.
	HeaderPresent string `json:"header_present,omitempty"`
	// HeaderAbsent fires when the named header is missing or has
	// only empty values.
	HeaderAbsent string `json:"header_absent,omitempty"`
	// QueryEquals fires when the named query param's first value
	// equals the given string.
	QueryEquals *QueryMatch `json:"query_equals,omitempty"`
	// QueryPresent / QueryAbsent mirror the header equivalents.
	QueryPresent string `json:"query_present,omitempty"`
	QueryAbsent  string `json:"query_absent,omitempty"`
}

// HeaderMatch is a (name, value) tuple used by HeaderEquals.
type HeaderMatch struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// QueryMatch mirrors HeaderMatch for query parameters.
type QueryMatch struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// RequestAction describes what happens when a rule matches.
type RequestAction struct {
	// Type is the discriminator. Must be one of:
	//   allow | block | set_header | del_header
	//   set_query | del_query | set_path | replace_path
	Type string `json:"type"`
	// Status is the HTTP status for Type="block". Defaults to 403.
	Status int `json:"status,omitempty"`
	// Body is the response body for Type="block".
	Body string `json:"body,omitempty"`
	// ContentType is the response Content-Type for Type="block".
	// Defaults to "application/json".
	ContentType string `json:"content_type,omitempty"`
	// Name is the header / query parameter name for the
	// corresponding set_/del_ actions.
	Name string `json:"name,omitempty"`
	// Pattern is the regexp pattern for Type="replace_path".
	Pattern string `json:"pattern,omitempty"`
	// Value is the new header / query / path value for set_* actions;
	// for Type="replace_path" it is the regexp replacement string
	// (Go regexp syntax, e.g. /$1 or /$name).
	Value string `json:"value,omitempty"`
	// CaptureTransforms applies literal string replacements to
	// selected regexp captures before Type="replace_path" expands
	// Value. Capture may be a number ("1") or a named capture
	// ("tail").
	CaptureTransforms []CaptureTransform `json:"capture_transforms,omitempty"`
}

// CaptureTransform mutates one replace_path capture before the
// action's replacement template is expanded.
type CaptureTransform struct {
	Capture string `json:"capture"`
	Find    string `json:"find"`
	Value   string `json:"value"`
}

// StaticCompat configures the plain config-data shim. The shim has
// no knobs today: base path lives on the parent, and query semantics
// mirror /data/{key} directly.
type StaticCompat struct{}

// ConsulCompat configures the read-only Consul KV shim. The shim
// mirrors the previous "/consul/v1/kv/*" endpoint that lived on the
// extracted public port: GET only, ?raw + ?variant + ?version +
// ?format supported, 404 returns an empty body.
type ConsulCompat struct{}

// ExternalCompat configures direct reads from a named External
// resource. The endpoint's path tail becomes the provider-specific
// path passed to ReadExternal. No config inheritance/render pipeline
// is involved.
//
// RawValue and ContentType are OPTIONAL per-endpoint overrides
// applied AFTER the provider's Read returns. They let one resource
// serve different shapes on different endpoints — e.g. the same GCP
// secret can be exposed as raw YAML on a /yaml/ listener and as the
// legacy JSON wrapper on a /json/ listener. Leave them empty/nil to
// inherit the provider's own configuration (e.g. GCP.RawValue +
// GCP.ContentType on the external resource).
type ExternalCompat struct {
	Resource string `json:"resource"`

	// RawValue overrides the provider's "raw vs wrapped" decision
	// for this endpoint. nil → inherit; true → force raw bytes (any
	// wrapper produced upstream is unwrapped when possible);
	// false → force the legacy `{"value": "<string>"}` JSON wrap.
	// Stored as *bool so absent serialises as "inherit" via the
	// omitempty tag.
	RawValue *bool `json:"raw_value,omitempty"`

	// ContentType overrides the HTTP Content-Type header on this
	// endpoint's responses. Empty → inherit Entry.ContentType.
	// When RawValue is forced false and ContentType is empty the
	// shim falls back to application/json (legacy wrap CT).
	ContentType string `json:"content_type,omitempty"`
}

// CustomCompat configures a user-authored Go-template response
// modifier. The template is rendered with text/template (NOT mugo —
// kept on a restricted FuncMap so it cannot reach the filesystem,
// env, or exec). Available template variables:
//
//	.Key             — resolved config key (path tail relative to base path)
//	.Variant         — variant query param ("" if absent)
//	.Version         — version query param ("" if absent)
//	.Raw             — bool, the "raw" query flag presence
//	.Format          — requested output format (after conversion)
//	.Data            — []byte, the resolved configuration body
//	.DataString      — string view of .Data
//	.DataB64         — base64-encoded .Data (handy for Consul-style envelopes)
//	.Found           — bool, false when the underlying key was not found
//	.ResolvedFormat  — the actual format pika produced for .Data
//	.Now             — current time on the server
type CustomCompat struct {
	// BodyTemplate is the Go text/template source rendered for every
	// successful resolution. Required.
	BodyTemplate string `json:"body_template"`
	// ContentType is the response Content-Type. Static; if empty,
	// defaults to "application/octet-stream".
	ContentType string `json:"content_type,omitempty"`
	// StatusOnMissing is the HTTP status returned when the
	// underlying key is not found. 0 → 404. Useful to set 204 or
	// 200+empty-body for clients that distrust 404s.
	StatusOnMissing int `json:"status_on_missing,omitempty"`
	// AllowFormatOverride lets the client pass ?format=json|yaml|toml
	// to convert the response body before rendering. When false the
	// stored format is always passed through to the template.
	AllowFormatOverride bool `json:"allow_format_override,omitempty"`
}

// EndpointAuth controls per-endpoint authentication. The three modes
// are mutually exclusive — pick the simplest one that fits.
type EndpointAuth struct {
	// Mode is one of:
	//
	//   "none"          — no authentication. Anyone who can reach
	//                     the listener can read.
	//   "bearer_token"  — require an "Authorization: Bearer <token>"
	//                     matching any pika API token with the
	//                     files.read capability. Goes through the
	//                     normal token storage path.
	//   "static_token"  — match the request token (header configurable
	//                     via HeaderName, default "X-Pika-Token") in
	//                     constant time against StaticTokens. Useful
	//                     for clients like consul-template that only
	//                     speak X-Consul-Token.
	Mode string `json:"mode"`
	// StaticTokens is the allowed-token list for Mode=="static_token".
	// Sealed at rest by internal/secret/settings_seal.go.
	StaticTokens []string `json:"static_tokens,omitempty"`
	// HeaderName is the request header to read the static token from.
	// Defaults to "X-Pika-Token". Common alternatives:
	// "X-Consul-Token" or "Authorization" for clients that require it.
	HeaderName string `json:"header_name,omitempty"`
}

type EndpointTLS struct {
	Enabled   bool `json:"enabled,omitempty"`
	AllowHTTP bool `json:"allow_http,omitempty"`
}

// Validate sanity-checks a PublicEndpoint. Returns a non-nil error
// wrapped with ErrBadRequest so the API layer maps it to 400.
func (p *PublicEndpoint) Validate() error {
	if p == nil {
		return fmt.Errorf("public endpoint: nil: %w", ErrBadRequest)
	}
	if strings.TrimSpace(p.Name) == "" {
		return fmt.Errorf("public endpoint: name is required: %w", ErrBadRequest)
	}
	if p.ListenPort < 1 || p.ListenPort > 65535 {
		return fmt.Errorf("public endpoint %q: port %d out of range: %w",
			p.Name, p.ListenPort, ErrBadRequest)
	}
	host := p.ListenHost
	if host == "" {
		host = "0.0.0.0"
	}
	if ip := net.ParseIP(host); ip == nil && host != "localhost" {
		return fmt.Errorf("public endpoint %q: invalid listen_host %q: %w",
			p.Name, host, ErrBadRequest)
	}
	bp := p.BasePath
	if bp == "" {
		bp = "/"
	}
	if !strings.HasPrefix(bp, "/") {
		return fmt.Errorf("public endpoint %q: base_path must start with /: %w",
			p.Name, ErrBadRequest)
	}
	if len(bp) > 1 && strings.HasSuffix(bp, "/") {
		return fmt.Errorf("public endpoint %q: base_path must not end with /: %w",
			p.Name, ErrBadRequest)
	}

	switch p.Mode {
	case "static":
		if p.Static == nil {
			return fmt.Errorf("public endpoint %q: static config block required for mode=static: %w",
				p.Name, ErrBadRequest)
		}
	case "consul":
		if p.Consul == nil {
			return fmt.Errorf("public endpoint %q: consul config block required for mode=consul: %w",
				p.Name, ErrBadRequest)
		}
	case "external":
		if p.External == nil {
			return fmt.Errorf("public endpoint %q: external config block required for mode=external: %w",
				p.Name, ErrBadRequest)
		}
		if strings.TrimSpace(p.External.Resource) == "" {
			return fmt.Errorf("public endpoint %q: external.resource is required: %w",
				p.Name, ErrBadRequest)
		}
	case "custom":
		if p.Custom == nil {
			return fmt.Errorf("public endpoint %q: custom config block required for mode=custom: %w",
				p.Name, ErrBadRequest)
		}
		if strings.TrimSpace(p.Custom.BodyTemplate) == "" {
			return fmt.Errorf("public endpoint %q: custom.body_template is required: %w",
				p.Name, ErrBadRequest)
		}
		// Parse-only check — runtime evaluation happens per request.
		if _, err := template.New("body").Parse(p.Custom.BodyTemplate); err != nil {
			return fmt.Errorf("public endpoint %q: invalid body_template: %v: %w",
				p.Name, err, ErrBadRequest)
		}
		if p.Custom.StatusOnMissing != 0 &&
			(p.Custom.StatusOnMissing < 100 || p.Custom.StatusOnMissing > 599) {
			return fmt.Errorf("public endpoint %q: status_on_missing %d not a valid HTTP status: %w",
				p.Name, p.Custom.StatusOnMissing, ErrBadRequest)
		}
	default:
		return fmt.Errorf("public endpoint %q: mode must be one of static|consul|external|custom (got %q): %w",
			p.Name, p.Mode, ErrBadRequest)
	}

	if p.RequestCheck != nil {
		for i, rule := range p.RequestCheck.Rules {
			if err := rule.validate(); err != nil {
				return fmt.Errorf("public endpoint %q: request_check.rules[%d]: %w: %w",
					p.Name, i, err, ErrBadRequest)
			}
		}
	}

	switch p.Auth.Mode {
	case "", "none", "bearer_token":
		// nothing to check.
	case "static_token":
		if len(p.Auth.StaticTokens) == 0 {
			return fmt.Errorf("public endpoint %q: auth.static_tokens must contain at least one token: %w",
				p.Name, ErrBadRequest)
		}
		for i, t := range p.Auth.StaticTokens {
			if strings.TrimSpace(t) == "" {
				return fmt.Errorf("public endpoint %q: auth.static_tokens[%d] is empty: %w",
					p.Name, i, ErrBadRequest)
			}
		}
	default:
		return fmt.Errorf("public endpoint %q: auth.mode must be one of none|bearer_token|static_token (got %q): %w",
			p.Name, p.Auth.Mode, ErrBadRequest)
	}

	if p.TLS.AllowHTTP && !p.TLS.Enabled {
		return fmt.Errorf("public endpoint %q: tls.allow_http requires tls.enabled: %w",
			p.Name, ErrBadRequest)
	}

	return nil
}

// validate sanity-checks a single rule. Returns an unwrapped
// error; the caller wraps with ErrBadRequest + position context.
func (r *RequestRule) validate() error {
	actions := r.effectiveActions()
	if len(actions) == 0 {
		return fmt.Errorf("rule requires at least one action")
	}
	for i := range actions {
		if err := validateRequestAction(&actions[i]); err != nil {
			if len(r.Actions) > 0 {
				return fmt.Errorf("actions[%d]: %w", i, err)
			}
			return err
		}
	}

	// Matcher tuples that require Name must have it.
	if r.When.HeaderEquals != nil && strings.TrimSpace(r.When.HeaderEquals.Name) == "" {
		return fmt.Errorf("when.header_equals.name is required")
	}
	if r.When.QueryEquals != nil && strings.TrimSpace(r.When.QueryEquals.Name) == "" {
		return fmt.Errorf("when.query_equals.name is required")
	}
	return nil
}

func (r *RequestRule) effectiveActions() []RequestAction {
	if len(r.Actions) > 0 {
		return r.Actions
	}
	if r.Then.Type == "" {
		return nil
	}
	return []RequestAction{r.Then}
}

func validateRequestAction(a *RequestAction) error {
	// Action type must be known and any name/value/status fields
	// it depends on must be populated.
	switch a.Type {
	case "allow":
		if len(a.CaptureTransforms) > 0 {
			return fmt.Errorf("capture_transforms are only valid on replace_path actions")
		}
		// nothing to require.
	case "block":
		if len(a.CaptureTransforms) > 0 {
			return fmt.Errorf("capture_transforms are only valid on replace_path actions")
		}
		if a.Status != 0 && (a.Status < 100 || a.Status > 599) {
			return fmt.Errorf("block status %d not a valid HTTP status", a.Status)
		}
	case "set_header", "del_header":
		if len(a.CaptureTransforms) > 0 {
			return fmt.Errorf("capture_transforms are only valid on replace_path actions")
		}
		if strings.TrimSpace(a.Name) == "" {
			return fmt.Errorf("%s action requires a header name", a.Type)
		}
		if a.Type == "set_header" && a.Value == "" {
			return fmt.Errorf("set_header requires a value (use del_header to remove)")
		}
	case "set_query", "del_query":
		if len(a.CaptureTransforms) > 0 {
			return fmt.Errorf("capture_transforms are only valid on replace_path actions")
		}
		if strings.TrimSpace(a.Name) == "" {
			return fmt.Errorf("%s action requires a query parameter name", a.Type)
		}
	case "set_path":
		if len(a.CaptureTransforms) > 0 {
			return fmt.Errorf("capture_transforms are only valid on replace_path actions")
		}
		v := strings.TrimSpace(a.Value)
		if v == "" {
			return fmt.Errorf("set_path requires a value")
		}
		if !strings.HasPrefix(v, "/") {
			return fmt.Errorf("set_path value must start with /")
		}
	case "replace_path":
		pattern := strings.TrimSpace(a.Pattern)
		if pattern == "" {
			return fmt.Errorf("replace_path requires a regex pattern")
		}
		re, err := regexp.Compile(pattern)
		if err != nil {
			return fmt.Errorf("replace_path invalid regex pattern: %v", err)
		}
		if a.Value == "" {
			return fmt.Errorf("replace_path requires a replacement value")
		}
		if err := validateCaptureTransforms(re, a.CaptureTransforms); err != nil {
			return err
		}
	default:
		return fmt.Errorf("unknown then.type %q (allowed: allow|block|set_header|del_header|set_query|del_query|set_path|replace_path)",
			a.Type)
	}
	return nil
}

func validateCaptureTransforms(re *regexp.Regexp, transforms []CaptureTransform) error {
	if len(transforms) == 0 {
		return nil
	}
	names := re.SubexpNames()
	for i, tr := range transforms {
		capture := strings.TrimSpace(tr.Capture)
		if capture == "" {
			return fmt.Errorf("capture_transforms[%d].capture is required", i)
		}
		if tr.Find == "" {
			return fmt.Errorf("capture_transforms[%d].find is required", i)
		}
		if idx, ok := captureIndex(names, capture); !ok || idx >= len(names) {
			return fmt.Errorf("capture_transforms[%d].capture %q does not exist in replace_path pattern", i, capture)
		}
	}
	return nil
}

func captureIndex(names []string, capture string) (int, bool) {
	if n, err := strconv.Atoi(capture); err == nil {
		return n, n >= 0 && n < len(names)
	}
	for i, name := range names {
		if i > 0 && name == capture {
			return i, true
		}
	}
	return -1, false
}

// ValidatePublicEndpoints checks a list of endpoints for both
// per-endpoint validity AND cross-endpoint conflicts (duplicate
// IDs, duplicate listen_host:port pairs).
func ValidatePublicEndpoints(eps []PublicEndpoint) error {
	ids := make(map[string]struct{}, len(eps))
	binds := make(map[string]string, len(eps)) // host:port -> name (for error context)
	for i := range eps {
		ep := &eps[i]
		if err := ep.Validate(); err != nil {
			return err
		}
		if ep.ID != "" {
			if _, dup := ids[ep.ID]; dup {
				return fmt.Errorf("public endpoint %q: duplicate id %q: %w",
					ep.Name, ep.ID, ErrBadRequest)
			}
			ids[ep.ID] = struct{}{}
		}
		host := ep.ListenHost
		if host == "" {
			host = "0.0.0.0"
		}
		bindKey := net.JoinHostPort(host, strconv.Itoa(ep.ListenPort))
		if other, dup := binds[bindKey]; dup {
			return fmt.Errorf("public endpoint %q: bind %s already used by %q: %w",
				ep.Name, bindKey, other, ErrBadRequest)
		}
		binds[bindKey] = ep.Name
	}
	return nil
}

// ErrPublicEndpointBindFailed is the sentinel the manager surfaces
// when one or more endpoints could not bind their TCP listener at
// reload time. Persistence already succeeded — this is a runtime
// notification.
var ErrPublicEndpointBindFailed = errors.New("public endpoint: one or more listeners failed to bind")
